{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim__deputados_SCD2\",\"dim__fornecedores\",\"dim__tipo_despesas\",\"fato__despesas\",\"medidas\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_f4f729e0-be91-406c-a45a-a3f56620bb10",
        "fromColumn": "sk_deputado",
        "fromTable": "fato__despesas",
        "toColumn": "sk_deputado",
        "toTable": "dim__deputados_SCD2"
      },
      {
        "name": "AutoDetected_5571b312-a70b-4ef9-901c-4e74ac15bdcb",
        "fromColumn": "cnpj_fornecedor",
        "fromTable": "fato__despesas",
        "toColumn": "cnpj_fornecedor",
        "toTable": "dim__fornecedores"
      },
      {
        "name": "AutoDetected_e28ec4f0-08f2-4328-8c05-bfc47da5c1a4",
        "fromColumn": "cod_tipo_despesa",
        "fromTable": "fato__despesas",
        "toColumn": "cod_tipo_despesa",
        "toTable": "dim__tipo_despesas"
      },
      {
        "name": "acd52841-9842-12b5-fe29-eedd20c371e2",
        "fromColumn": "dt_despesa",
        "fromTable": "fato__despesas",
        "toColumn": "Date",
        "toTable": "dim__calendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "dim__deputados_SCD2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id_deputado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d09e7313-87bb-47c0-8a5f-2aa77ac13768",
            "sourceColumn": "id_deputado",
            "summarizeBy": "sum"
          },
          {
            "name": "nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fe56489-43b7-47bc-a1d0-5ba84eb014d8",
            "sourceColumn": "nome",
            "summarizeBy": "none"
          },
          {
            "name": "sigla_partido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56cb2181-14bc-42f4-882e-5b6689903e12",
            "sourceColumn": "sigla_partido",
            "summarizeBy": "none"
          },
          {
            "name": "uf",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de3d09a3-cee7-4ee1-bf59-48201b078d08",
            "sourceColumn": "uf",
            "summarizeBy": "none"
          },
          {
            "name": "url_foto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "93e937eb-726e-4eb5-8577-c559d9a4ce7c",
            "sourceColumn": "url_foto",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be8fa0f0-fda7-4a5e-8567-44cd951bf750",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5bb73d1c-3d3e-443d-b285-93a67b403f45",
            "sourceColumn": "idade",
            "summarizeBy": "sum"
          },
          {
            "name": "escolaridade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7ebc73d-e111-4c74-a34b-cbb4c8646d3f",
            "sortByColumn": "ordem_escolaridade",
            "sourceColumn": "escolaridade",
            "summarizeBy": "none"
          },
          {
            "name": "ordem_escolaridade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48802170-99c0-4be6-b682-ce34dbebb599",
            "sourceColumn": "ordem_escolaridade",
            "summarizeBy": "sum"
          },
          {
            "name": "faixa_idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20007c54-ea69-47c9-93b0-2fbed5cfb213",
            "sourceColumn": "faixa_idade",
            "summarizeBy": "none"
          },
          {
            "name": "situacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0cd0fff-cd8f-4c33-81bc-2f65eeee0f53",
            "sourceColumn": "situacao",
            "summarizeBy": "none"
          },
          {
            "name": "condicao_eleitoral",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04ac0dbd-0aaf-4f39-a7d6-f62e37fcf291",
            "sourceColumn": "condicao_eleitoral",
            "summarizeBy": "none"
          },
          {
            "name": "dt_inicio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5dc53d0e-48f0-4102-b28f-4308c532c281",
            "sourceColumn": "dt_inicio",
            "summarizeBy": "none"
          },
          {
            "name": "sk_deputado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dca6fa56-5de4-436c-ae71-af18379b3fe8",
            "sourceColumn": "sk_deputado",
            "summarizeBy": "none"
          },
          {
            "name": "dt_fim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0461dd2c-7a82-4078-9069-b457a211a143",
            "sourceColumn": "dt_fim",
            "summarizeBy": "none"
          },
          {
            "name": "versao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4427cc74-e55e-44c8-82d4-8ce634855a70",
            "sourceColumn": "versao",
            "summarizeBy": "sum"
          },
          {
            "name": "status_atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3c3ad507-3d7b-45b7-a4f0-dabeffcec8ab",
            "sourceColumn": "status_atual",
            "summarizeBy": "none"
          },
          {
            "name": "Pais Região",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"BRAZIL - \" & dim__deputados_SCD2[uf]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3d3db13a-b0c5-4baf-bb34-a361ebf665ec",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "43582f36-e0bc-43c2-b93c-e19db876c01f",
        "partitions": [
          {
            "name": "dim__deputados_SCD2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PostgreSQL.Database(\"dpg-cpmrvpg8fa8c73anins0-a.oregon-postgres.render.com\", \"dados_abertos\"),",
                "    dbt_gold_dim__deputados_SCD2 = Fonte{[Schema=\"dbt_gold\",Item=\"dim__deputados_SCD2\"]}[Data]",
                "in",
                "    dbt_gold_dim__deputados_SCD2"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim__fornecedores",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "cnpj_fornecedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93994990-88d4-4a2f-84b2-0bac1567383c",
            "sourceColumn": "cnpj_fornecedor",
            "summarizeBy": "none"
          },
          {
            "name": "nome_fornecedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ea2541e-e0e0-46c4-a802-ac0774b4ccbc",
            "sourceColumn": "nome_fornecedor",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5b4d4405-47ac-483c-a536-ec8f9ecdecde",
        "partitions": [
          {
            "name": "dim__fornecedores",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PostgreSQL.Database(\"dpg-cpmrvpg8fa8c73anins0-a.oregon-postgres.render.com\", \"dados_abertos\"),",
                "    dbt_gold_dim__fornecedores = Fonte{[Schema=\"dbt_gold\",Item=\"dim__fornecedores\"]}[Data]",
                "in",
                "    dbt_gold_dim__fornecedores"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim__tipo_despesas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "cod_tipo_despesa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a5d83a5-415c-4821-bb6c-3c60c86dd898",
            "sourceColumn": "cod_tipo_despesa",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_despesa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9da66b90-964c-4c5b-9228-c50f56891f4f",
            "sourceColumn": "tipo_despesa",
            "summarizeBy": "none"
          },
          {
            "name": "agrupamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bd40d03-421b-4f5c-94bf-77046fa962b0",
            "sourceColumn": "agrupamento",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0272373b-221e-43d9-b42e-21f78e89ab06",
        "partitions": [
          {
            "name": "dim__tipo_despesas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PostgreSQL.Database(\"dpg-cpmrvpg8fa8c73anins0-a.oregon-postgres.render.com\", \"dados_abertos\"),",
                "    dbt_gold_dim__tipo_despesas = Fonte{[Schema=\"dbt_gold\",Item=\"dim__tipo_despesas\"]}[Data]",
                "in",
                "    dbt_gold_dim__tipo_despesas"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fato__despesas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "id_deputado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ee51224-26ad-4927-9684-d4428c13723e",
            "sourceColumn": "id_deputado",
            "summarizeBy": "sum"
          },
          {
            "name": "dt_despesa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2f112c22-af7a-4664-9641-c5c0c813a9e6",
            "sourceColumn": "dt_despesa",
            "summarizeBy": "none"
          },
          {
            "name": "cnpj_fornecedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f28d48c4-5f81-4c64-a518-ad2afe909b3c",
            "sourceColumn": "cnpj_fornecedor",
            "summarizeBy": "none"
          },
          {
            "name": "vlr_liquido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "73ea072f-1628-4caa-9534-efa2cb30b983",
            "sourceColumn": "vlr_liquido",
            "summarizeBy": "sum"
          },
          {
            "name": "cod_tipo_despesa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "826f472a-c290-4b1b-9d71-9d48ec8c9e27",
            "sourceColumn": "cod_tipo_despesa",
            "summarizeBy": "none"
          },
          {
            "name": "sk_deputado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ded4a930-3853-4322-822e-5b30aaf0c9a2",
            "sourceColumn": "sk_deputado",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e1b81a34-9216-484e-b6b7-e486de2af8aa",
        "partitions": [
          {
            "name": "fato__despesas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PostgreSQL.Database(\"dpg-cpmrvpg8fa8c73anins0-a.oregon-postgres.render.com\", \"dados_abertos\"),",
                "    dbt_gold_fato__despesas = Fonte{[Schema=\"dbt_gold\",Item=\"fato__despesas\"]}[Data]",
                "in",
                "    dbt_gold_fato__despesas"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "3a2ae0c0-1c45-4b05-9361-5f493e955f29",
        "measures": [
          {
            "name": "Deputados",
            "displayFolder": "basicas",
            "expression": "DISTINCTCOUNT( dim__deputados_SCD2[id_deputado] )",
            "formatString": "#,0",
            "lineageTag": "10ce344f-f24c-4188-a513-065895a84e98"
          },
          {
            "name": "Deputados com Despesas",
            "displayFolder": "basicas",
            "expression": [
              "",
              "DISTINCTCOUNT(fato__despesas[id_deputado])"
            ],
            "formatString": "0",
            "lineageTag": "4dcb9ce4-480d-4f18-9976-e328fec667be"
          },
          {
            "name": "Despesas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "displayFolder": "basicas",
            "expression": [
              "",
              "    SUM(fato__despesas[vlr_liquido])"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "edc5ae3c-e138-491c-a9e6-6b48aaee0892"
          },
          {
            "name": "Partidos",
            "displayFolder": "basicas",
            "expression": "DISTINCTCOUNT( dim__deputados_SCD2[sigla_partido] )",
            "formatString": "0",
            "lineageTag": "d5bf3da4-28de-445c-8388-a1c05238f6a0"
          },
          {
            "name": "Despesas Dept Float",
            "displayFolder": "DataViz",
            "expression": "[Despesas / Deputado com Despesas / Mês]",
            "lineageTag": "363af102-1d40-45c2-b614-6fe75a8d8af5"
          },
          {
            "name": "Despesas Deputado Float",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "DataViz",
            "expression": "[Despesas]",
            "lineageTag": "47ca04c8-dd91-4805-a179-f598025d65e2"
          },
          {
            "name": "EixoDespesasDeputadosPeriodo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "DataViz",
            "expression": [
              "",
              "MAXX( ",
              "    ALLSELECTED(  dim__calendario[Ano], dim__calendario[Mês Abreviado] ) , [Despesas]",
              ") * 1.3"
            ],
            "lineageTag": "70f14cd3-6906-4a54-afb8-39e62c588250"
          },
          {
            "name": "EixoMediaDespesasDeputadosUf",
            "displayFolder": "DataViz",
            "expression": [
              "",
              "MAXX( ",
              "    VALUES( dim__deputados_SCD2[uf] ),",
              "    MAX( [Despesas / Deputado com Despesas / Mês] , [Despesas Medianas por Deputado] )",
              ") * 1.20"
            ],
            "lineageTag": "f68151c4-99f4-47fe-8dcf-883d8ec07c68"
          },
          {
            "name": "EixoMediaIdade",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "DataViz",
            "expression": [
              "",
              "MAXX( ",
              "    VALUES( dim__deputados_SCD2[faixa_idade] ),",
              "    [Deputados com Despesas]",
              ") * 1.30"
            ],
            "lineageTag": "97126574-be5d-4b27-9d4f-42474c74f24d"
          },
          {
            "name": "Faltante",
            "displayFolder": "DataViz",
            "expression": [
              "",
              "1 - [(%) Deputados]"
            ],
            "lineageTag": "26ca0a45-3999-4813-97d5-c4eed3465386"
          },
          {
            "name": "Posição",
            "displayFolder": "DataViz",
            "expression": [
              "",
              "IF(",
              "    ISINSCOPE(dim__deputados_SCD2[nome]),",
              "    RANKX(",
              "        ALL(dim__deputados_SCD2),",
              "        [Despesas],",
              "        ,",
              "        DESC",
              "    ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "48c235c2-f417-44d6-975e-aa372d8cb3d4"
          },
          {
            "name": "Rótulo MoM",
            "displayFolder": "DataViz",
            "expression": "[Despesas]",
            "formatStringDefinition": {
              "expression": [
                "VAR _num = [MoM Despesas]",
                "",
                "VAR _icon = SWITCH(",
                "     TRUE(),",
                "     _num > 0, \"▲\",",
                "     _num < 0, \"▼\",",
                "     \"●\"",
                ")",
                "VAR _num_format = IF(_num < 0, FORMAT(ABS(_num),\"0%\"), FORMAT(_num,\"0%\"))",
                "",
                "RETURN",
                "\"\"\"\" &  _icon & \" \" & _num_format & \"\"\"\""
              ]
            },
            "lineageTag": "52deb8fc-cda9-44ef-9617-7af695999204"
          },
          {
            "name": "TituloGraficoIdade",
            "displayFolder": "DataViz",
            "expression": [
              "",
              "\"Deputados por Idade ㅤㅤㅤㅤㅤ \" & \"( média - \" & [Media idade] & \" anos )\""
            ],
            "lineageTag": "c7320064-b981-4b4d-8f17-c8f8083e6538"
          },
          {
            "name": "(%) Deputados",
            "displayFolder": "estatisticas",
            "expression": [
              "",
              "",
              "VAR _TotalDeputados =",
              "CALCULATE(",
              "    DISTINCTCOUNT( fato__despesas[id_deputado] ),",
              "    ALLSELECTED(fato__despesas)",
              ")",
              "",
              "",
              "RETURN",
              "DIVIDE( [Deputados] , _TotalDeputados )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "89067460-c155-4443-b01b-46584bbd8ede"
          },
          {
            "name": "(%) Despesas",
            "displayFolder": "estatisticas",
            "expression": [
              "",
              "",
              "VAR _Total =",
              "CALCULATE(",
              "    SUM(fato__despesas[vlr_liquido]),",
              "    ALLSELECTED(fato__despesas)",
              ")",
              "",
              "",
              "RETURN",
              "DIVIDE( [Despesas] , _Total )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e423e323-8d69-4a53-b222-c23ddb8341ea"
          },
          {
            "name": "Despesas / Deputado com Despesas / Mês",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "displayFolder": "estatisticas",
            "expression": [
              "",
              "AVERAGEX(",
              "    VALUES(dim__calendario[OffsetMes]) ,",
              "    DIVIDE( [Despesas] , [Deputados com Despesas] )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "ce6939c0-bd9e-4bda-8b80-e149670d40ea"
          },
          {
            "name": "Despesas Medianas por Deputado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "displayFolder": "estatisticas",
            "expression": [
              "",
              "VAR despesasPorDeputado = ",
              "    SUMMARIZE(",
              "        'fato__despesas',",
              "        dim__calendario[OffsetMes],",
              "        'fato__despesas'[id_deputado],",
              "        \"DespesaTotal\", SUM('fato__despesas'[vlr_liquido])",
              "    )",
              "RETURN",
              "    MEDIANX(despesasPorDeputado, [DespesaTotal])"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "1abd2590-ba4b-400a-82ba-7134c2413e65"
          },
          {
            "name": "LM Despesas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "estatisticas",
            "expression": [
              "",
              "CALCULATE(",
              "    [Despesas],",
              "    DATEADD(dim__calendario[date], -1, MONTH )",
              ")"
            ],
            "lineageTag": "10684829-477c-49ef-954b-b9bb2381d029"
          },
          {
            "name": "Media idade",
            "displayFolder": "estatisticas",
            "expression": [
              "",
              "INT( AVERAGE( dim__deputados_SCD2[idade] ) )"
            ],
            "formatString": "0",
            "lineageTag": "a1c5e651-1258-409b-a979-03b7ee84ae85"
          },
          {
            "name": "MoM Despesas",
            "displayFolder": "estatisticas",
            "expression": [
              "",
              "DIVIDE( [Despesas] - [LM Despesas] , [LM Despesas] )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0da653de-ae7f-40aa-9b7b-e25316383d07"
          }
        ],
        "partitions": [
          {
            "name": "medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(Fonte,{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim__calendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1ab5e57f697546b0a6ccb611c745bc46"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "70f531c5-5978-4a9b-acf3-6b135ed88242",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5ed91a86-d4e9-4e76-9e87-3ac7b2bf13d3",
            "sourceColumn": "[Dia]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "802aa10c-ddae-4101-955e-b1562472364c",
            "sortByColumn": "Dia da Semana",
            "sourceColumn": "[Dia nome]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "498d7d27-6241-4f1b-b2cf-9b1305349ec1",
            "sourceColumn": "[Dia da Semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Semana Num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6daf90a5-7381-483d-b3fa-eb1a91b28310",
            "sourceColumn": "[Semana Num]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês Num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5a647c43-00f2-45c8-82cc-436ea2f29884",
            "sourceColumn": "[Mês Num]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6fbd7eb8-a1ba-459b-8e13-954be31a2043",
            "sourceColumn": "[Mês]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "52874ea2-70a3-43c7-80d7-ff75a0e9a907",
            "sortByColumn": "Mês Num",
            "sourceColumn": "[Mês Abreviado]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a5fd0c4c-0dc3-4ca8-9ab1-ffa347f0c7b3",
            "sourceColumn": "[Trimestre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "907fd08e-b81b-4ca4-bea7-02da8504435e",
            "sourceColumn": "[Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AnoMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c449b0fa-9f59-4724-b018-87aa5144709b",
            "sourceColumn": "[AnoMes]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "378ff70c-f417-45ba-84c0-97beb581c260",
            "sourceColumn": "[Tipo]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "OffsetMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "84d0b699-fe83-448f-8c00-06fc58af7bf4",
            "sourceColumn": "[OffsetMes]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês Seleção",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "21657f78-1c4d-4a35-bdfc-be0cd2135607",
            "sortByColumn": "Mês Num",
            "sourceColumn": "[Mês Seleção]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "1105bbf1-7926-4673-8c6e-dbd04d8e77f0",
        "partitions": [
          {
            "name": "dim__calendario",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "",
                "    ADDCOLUMNS(",
                "        CALENDAR(",
                "                    DATE(",
                "                        YEAR(",
                "                                MIN(fato__despesas[dt_despesa])",
                "                                ),1,1",
                "                        ),",
                "                    DATE(YEAR(TODAY()),12,31)",
                "                ),",
                "        \"Dia\", DAY([date]),",
                "        \"Dia nome\", FORMAT([date], \"dddd\",\"pt-BR\"),",
                "        \"Dia da Semana\", WEEKDAY([date]),",
                "        \"Semana Num\", WEEKNUM([date]),",
                "        \"Mês Num\", MONTH([date]),",
                "        \"Mês\", FORMAT([Date], \"mmmm\",\"pt-BR\"),",
                "        \"Mês Abreviado\", FORMAT([Date], \"mmm\",\"pt-BR\"),",
                "        \"Trimestre\", QUARTER([Date]),",
                "        \"Ano\", YEAR([Date]),",
                "        \"AnoMes\", YEAR([Date]) * 100 + MONTH([date]),",
                "        \"Tipo\", SWITCH(",
                "                        TRUE(),",
                "                        [Date]>TODAY(),",
                "                        \"Futuro\",",
                "                        \"Passado\"",
                "        ),",
                "        \"OffsetMes\",",
                "                (YEAR([Date])-YEAR(MIN(fato__despesas[dt_despesa])))*12+MONTH([Date]),",
                "        \"Mês Seleção\",",
                "                IF(MONTH([Date])=MONTH(TODAY()) && YEAR([Date])=YEAR(TODAY()) ,\"mês atual\",FORMAT([date], \"mmmm\",\"pt-BR\"))",
                "    )"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}