version: '3'

services:
  postgres:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - ${PORT}:${PORT}
    networks:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEFAULTMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
    ports:
      - 5050:5050
    networks:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DBT_CONTEXT: ${DBT_CONTEXT}
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
      DATABASE: ${DATABASE}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      SCHEMA: ${SCHEMA}
      TREADS: ${TREADS}
      TYPE: ${TYPE}
      TARGET: ${TARGET}
      DBT_PROFILES_DIR: ${DBT_PROFILES_DIR}
      SAMPLE_RUN: ${SAMPLE_RUN}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    command: ["task", "docker_run"]
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
