name: Deploy dbt docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.5

    - name: Install dbt
      run: pip install dbt-postgres

    - run: pip install poetry
    - run: poetry install
    - run: poetry run mkdocs gh-deploy --force

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "
        dbt_dados_abertos_camara:
          target: dev
          outputs:
            dev:
              type: postgres
              host: ${{ secrets.HOSTNAME }}
              port: ${{ secrets.PORT }}
              user: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              dbname: ${{ secrets.DATABASE }}
              schema: ${{ secrets.SCHEMA }}
              threads: ${{ secrets.TREADS }}
        " > ~/.dbt/profiles.yml
