name: Deploy dbt docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dbt
      run: pip install dbt-postgres

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "
        dbt_dados_abertos_camara:
          target: dev
          outputs:
            dev:
              type: postgres
              host: ${{ secrets.HOSTNAME }}
              port: ${{ secrets.PORT }}
              user: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              dbname: ${{ secrets.DATABASE }}
              schema: ${{ secrets.SCHEMA }}
              threads: ${{ secrets.TREADS }}
        " > ~/.dbt/profiles.yml

    - name: Install dependencies and generate docs
      run: |
        cd dbt_dados_abertos_camara
        dbt deps
        dbt docs generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PATH }}
        publish_dir: ./dbt_dados_abertos_camara/target
